import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import Header from '@/components/header';

const mont = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Bual | Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={mont.className}>{children}</body>
    </html>
  );
}
